version: '3.4'

services:
  muvin:
    image: muvin
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 8020:8020
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "server.js"]
